### ISSUE TITLE
shoukaku - ADD, ERROR: MODULE (Typescript)

### ISSUE THREAD

**Issue by LucasB25** [brblacky/lavamusic#423]
### Bug description 

```
[27/08/2023] [03:31:03] [InteractionCreate.js] [Lavamusic] › ✖  error     TypeError: Cannot read properties of undefined (reading 'player') 
    at Leave.run (file:///home/pi/lavamusic/dist/commands/music/Leave.js:34:107)
    at InteractionCreate.run (file:///home/pi/lavamusic/dist/events/client/InteractionCreate.js:142:31)
    
```
- We can put everyone or here as a DJ
![image](https://user-images.githubusercontent.com/50886682/224702226-81fdf67a-effb-4999-981e-6b31537a8742.png)

![image](https://github.com/brblacky/lavamusic/assets/50886682/936fcba7-7903-4c5e-a839-facb88960684)

    
- While playing a music using auto play the bot destroys the music and this disconnects
  - The auto play is to redo it does anything cause crashes without reason born respect by the music requested by the author and causes worries on the automatic music search
- I would like to suggest these two new effects if they are not yet implemented. It consists of Reverb and Chorus.
- Automatic message removal from the setup channel is not always done

**MUSIC**
- lyrics.js

**Comment by brblacky** [comment]
> ### Bug description
> We can put everyone or here as a DJ ![image](https://user-images.githubusercontent.com/50886682/224702226-81fdf67a-effb-4999-981e-6b31537a8742.png)
> 
> ```
> [13/03/2023] [13:26:36] [MessageCreate.js] [Lavamusic] » ✖  error     TypeError: Cannot read properties of undefined (reading 'connection') 
>     at Join.run (C:\Users\LucasB25\Desktop\panaisnew\src\commands\music\Join.ts:38:127)
>     at MessageCreate.run (C:\Users\LucasB25\Desktop\panaisnew\src\events\client\MessageCreate.ts:119:27)
> ```
> 
> ```
> [13/03/2023] [17:12:22] [MessageCreate.js] [Lavamusic] » ✖  error     TypeError: Cannot read properties of undefined (reading 'forEach') 
>     at RoleAll.run (C:\Users\LucasB25\Desktop\panaisnew\src\commands\moderator\RoleAll.ts:64:23)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at MessageCreate.run (C:\Users\LucasB25\Desktop\panaisnew\src\events\client\MessageCreate.ts:120:20)
> ```
> 
> ```
> [13/03/2023] [17:01:01] [Lavamusic.js] [Lavamusic] » ✖  error     DiscordAPIError[50035]: Invalid Form Body 
> options[1][APPLICATION_COMMAND_OPTIONS_TYPE_INVALID]: Sub-command and sub-command group option types are mutually exclusive to all other types
>     at SequentialHandler.runRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:498:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at SequentialHandler.queueRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:198:11)
>     at REST.request (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\REST.ts:343:20)
>     at Lavamusic.<anonymous> (C:\Users\LucasB25\Desktop\panaisnew\src\structures\Lavamusic.ts:92:17)
> ```
> 
> ```
> [13/03/2023] [13:26:51] [aitiCrash.js] [Lavamusic] » ✖  error     Unhandled Rejection at: Promise {
>   <rejected> Error: The voice connection is not established in 15 seconds
>       at Connection.connect (C:\Users\LucasB25\Desktop\panaisnew\node_modules\shoukaku\src\guild\Connection.ts:169:23)
>       at Node.joinChannel (C:\Users\LucasB25\Desktop\panaisnew\node_modules\shoukaku\src\node\Node.ts:244:13)
>       at Queue.create (C:\Users\LucasB25\Desktop\panaisnew\src\structures\Queue.ts:31:28)
> } reason: Error: The voice connection is not established in 15 seconds
>     at Connection.connect (C:\Users\LucasB25\Desktop\panaisnew\node_modules\shoukaku\src\guild\Connection.ts:169:23)
>     at Node.joinChannel (C:\Users\LucasB25\Desktop\panaisnew\node_modules\shoukaku\src\node\Node.ts:244:13)
>     at Queue.create (C:\Users\LucasB25\Desktop\panaisnew\src\structures\Queue.ts:31:28)
> ```
> 
> ```
> [13/03/2023] [13:28:47] [MessageCreate.js] [Lavamusic] » ✖  error     TypeError: Cannot read properties of undefined (reading 'id') 
>     at Dj.run (C:\Users\LucasB25\Desktop\panaisnew\src\commands\config\Dj.ts:82:59)
>     at MessageCreate.run (C:\Users\LucasB25\Desktop\panaisnew\src\events\client\MessageCreate.ts:119:27)
> ```
> 
> ```
> [13/03/2023] [17:17:23] [aitiCrash.js] [Lavamusic] » ✖  error     Unhandled Rejection at: Promise {
>   <rejected> DiscordAPIError[10008]: Unknown Message
>       at SequentialHandler.runRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:498:11)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at SequentialHandler.queueRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:198:11)
>       at REST.request (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\REST.ts:343:20)
>       at async MessageManager._fetchSingle (C:\Users\LucasB25\Desktop\panaisnew\node_modules\discord.js\src\managers\MessageManager.js:102:18)
>       at TrackEnd.run (C:\Users\LucasB25\Desktop\panaisnew\src\events\player\TrackEnd.ts:22:19) {
>     rawError: { message: 'Unknown Message', code: 10008 },
>     code: 10008,
>     status: 404,
>     method: 'GET',
>     url: 'https://discord.com/api/v10/channels/1081895602817867786/messages/1084872057587777536',
>     requestBody: { files: undefined, json: undefined }
>   }
> } reason: DiscordAPIError[10008]: Unknown Message
>     at SequentialHandler.runRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:498:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at SequentialHandler.queueRequest (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:198:11)
>     at REST.request (C:\Users\LucasB25\Desktop\panaisnew\node_modules\@discordjs\rest\src\lib\REST.ts:343:20)
>     at async MessageManager._fetchSingle (C:\Users\LucasB25\Desktop\panaisnew\node_modules\discord.js\src\managers\MessageManager.js:102:18)
>     at TrackEnd.run (C:\Users\LucasB25\Desktop\panaisnew\src\events\player\TrackEnd.ts:22:19) {
>   rawError: { message: 'Unknown Message', code: 10008 },
>   code: 10008,
>   status: 404,
>   method: 'GET',
>   url: 'https://discord.com/api/v10/channels/1081895602817867786/messages/1084872057587777536',
>   requestBody: { files: undefined, json: undefined }
> }
> ```
> 
> ### Feature added
> * Added a character limit to setprefix
> * Added the sharding system
> 
> **CONFIG**
> 
> * setup
> 
> **INFO**
> 
> * node.js
> 
> **MUSIC**
> 
> * lyrics.js
> * search.js
> * grab
> * loop

Fixed all

**Comment by LucasB25** [comment]
for the most part yes. I found two more concerns in addition to the one that is not yet resolved. This affects 247 and autoplay
